"""Add progress to projects

Revision ID: 23be6c96c241
Revises: b8a70b5a4e6f
Create Date: 2026-05-13 01:39:03.791274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23be6c96c241'
down_revision: Union[str, None] = 'b8a70b5a4e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('progress', sa.Integer(), nullable=True))
    op.execute("UPDATE projects SET progress = 0")
    op.alter_column('projects', 'progress', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'progress')
    # ### end Alembic commands ###