"""Add start_date to projects

Revision ID: a3830aa9f99c
Revises: 23be6c96c241
Create Date: 2026-05-13 01:47:34.181473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3830aa9f99c'
down_revision: Union[str, None] = '23be6c96c241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###