"""Add due_date to projects

Revision ID: e6229a35c3a7
Revises: a3830aa9f99c
Create Date: 2026-05-13 02:24:13.542549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6229a35c3a7'
down_revision: Union[str, None] = 'a3830aa9f99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('due_date', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'due_date')
    # ### end Alembic commands ###